#pragma once
#include "types.h"

namespace tfe::core {

    /**
     * @brief The total number of possible states for a single row.
     * 
     * A row has 4 tiles. Each tile uses 4 bits (values 0-15).
     * Total bits = 4 * 4 = 16 bits.
     * 2^16 = 65536 possible combinations.
     */
    static constexpr int TABLE_SIZE = 1 << 16; 

    /**
     * @class LookupTable
     * @brief Provides pre-computed results for row operations to optimize performance.
     *
     * Instead of calculating the result of a move or score evaluation for every single
     * row during runtime (which involves loops and conditionals), we pre-calculate
     * the results for all 65536 possible row configurations.
     * 
     * This transforms complex logic into O(1) array lookups, which is crucial for
     * the AI solver to explore millions of states per second.
     */
    class LookupTable {
    public:
        /**
         * @brief Initializes all lookup tables.
         * Must be called once before using any table.
         */
        static void init();

        /**
         * @brief Loads pre-trained heuristic weights from a file.
         * @param filepath Path to the weights file (usually generated by a trainer).
         * @return True if loaded successfully, False otherwise.
         */
        static bool loadWeights(const char* filepath);

        // --- Row Tables (Horizontal Moves) ---
        // Input: 16-bit row index. Output: 16-bit resulting row.

        /**
         * @brief Returns the result of moving a row Left.
         */
        static Row moveLeftTable[TABLE_SIZE];

        /**
         * @brief Returns the result of moving a row Right.
         */
        static Row moveRightTable[TABLE_SIZE];

        // --- Column Tables (Vertical Moves) ---
        // Input: 16-bit "packed" column (extracted from rows). 
        // Output: 64-bit sparse column ready to be OR-ed into the Bitboard.
        
        /**
         * @brief Returns the result of moving a column Up.
         * Output is shifted to correspond to Column 0 in the 64-bit board.
         * (e.g., input 0x1234 -> output 0x0004000300020001)
         */
        static Bitboard colUpTable[TABLE_SIZE];

        /**
         * @brief Returns the result of moving a column Down.
         */
        static Bitboard colDownTable[TABLE_SIZE];

        // --- Scoring Tables ---

        /**
         * @brief Returns the score gained by a Left move on a specific row.
         */
        static int scoreTable[TABLE_SIZE];

        /**
         * @brief Returns the score gained by a Right move.
         */
        static int scoreRightTable[TABLE_SIZE];

        // --- AI Evaluation Tables ---

        /**
         * @brief Returns the heuristic score of a row (for Expectimax).
         */
        static float heuristicTable[TABLE_SIZE];

        /**
         * @brief Returns the "Square" table value (used in some tuple network variants).
         */
        static float squareTable[TABLE_SIZE];

    private:
        /**
         * @brief Computes values for a single row configuration during initialization.
         * @param row The 16-bit row index.
         */
        static void initRow(int row);
    };
}  // namespace tfe::core